"""Fix primary key in Permanent and Contractuel

Revision ID: eee23a97f43d
Revises: 
Create Date: 2025-05-23 00:06:12.752421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eee23a97f43d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractuels', sa.Column('idcontractuel', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_contractuels_idcontractuel'), 'contractuels', ['idcontractuel'], unique=False)
    op.drop_column('contractuels', 'Pchiff')
    op.drop_column('contractuels', 'Pdate_effet')
    op.drop_column('contractuels', 'Pdate_chiff')
    op.add_column('employes', sa.Column('Cchiff', sa.String(length=50), nullable=True))
    op.add_column('employes', sa.Column('Cdate_chiff', sa.Date(), nullable=True))
    op.add_column('employes', sa.Column('Cdate_effet', sa.Date(), nullable=True))
    op.add_column('permanents', sa.Column('idpermanent', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_permanents_idpermanent'), 'permanents', ['idpermanent'], unique=False)
    op.drop_column('permanents', 'Cchiff')
    op.drop_column('permanents', 'Cdate_effet')
    op.drop_column('permanents', 'Cdate_chiff')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanents', sa.Column('Cdate_chiff', sa.DATE(), nullable=True))
    op.add_column('permanents', sa.Column('Cdate_effet', sa.DATE(), nullable=True))
    op.add_column('permanents', sa.Column('Cchiff', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_index(op.f('ix_permanents_idpermanent'), table_name='permanents')
    op.drop_column('permanents', 'idpermanent')
    op.drop_column('employes', 'Cdate_effet')
    op.drop_column('employes', 'Cdate_chiff')
    op.drop_column('employes', 'Cchiff')
    op.add_column('contractuels', sa.Column('Pdate_chiff', sa.DATE(), nullable=True))
    op.add_column('contractuels', sa.Column('Pdate_effet', sa.DATE(), nullable=True))
    op.add_column('contractuels', sa.Column('Pchiff', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contractuels_idcontractuel'), table_name='contractuels')
    op.drop_column('contractuels', 'idcontractuel')
    # ### end Alembic commands ###
