"""update tables : employes , contractuels , permanents

Revision ID: fc175a5606c1
Revises: eee23a97f43d
Create Date: 2025-05-23 00:16:43.543546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc175a5606c1'
down_revision: Union[str, None] = 'eee23a97f43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contractuels', 'idemploye',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_contractuels_idcontractuel'), table_name='contractuels')
    op.create_unique_constraint(None, 'contractuels', ['idemploye'])
    op.alter_column('permanents', 'idemploye',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_permanents_idpermanent'), table_name='permanents')
    op.create_unique_constraint(None, 'permanents', ['idemploye'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permanents', type_='unique')
    op.create_index(op.f('ix_permanents_idpermanent'), 'permanents', ['idpermanent'], unique=False)
    op.alter_column('permanents', 'idemploye',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'contractuels', type_='unique')
    op.create_index(op.f('ix_contractuels_idcontractuel'), 'contractuels', ['idcontractuel'], unique=False)
    op.alter_column('contractuels', 'idemploye',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
